### ISSUE TITLE
Key/Values in the global section got assigned a nil section on the data dictionary

### ISSUE THREAD

**Issue by gcotelli** [ctSkennerton/INI-Parser#3]
For example parsing:

```smalltalk
(IniReader on: 'key = value' readStream ) parse
```
produces something like 
```smalltalk
Dictionary new
  at: nil put: ( { 'key' -> 'value' } asDictionary );
  yourself
```
What do you think about assigning them an empty section instead of nil?

**Comment by ctSkennerton** [comment]
It seems reasonable. I looked at how [java does it](http://commons.apache.org/proper/commons-configuration/apidocs/org/apache/commons/configuration2/INIConfiguration.html) and they return a custom object that can handle globals so I guess it's my own fault for keeping it simple by returning a nested dict.

**Comment by gcotelli** [comment]
I think at least creating something like
```smalltalk
Dictionary new
  at: '' put: ( { 'key' -> 'value' } asDictionary );
  yourself
```
would avoid having to check for nil. At least this would work for my use case. 

If you're ok I can produce a PR changing this behavior.

**Comment by ctSkennerton** [comment]
Sure happy to merge it.
